
package com.dmi.tommy.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.6-redhat-3
 * Thu Dec 05 10:11:56 EST 2013
 * Generated source version: 2.6.6-redhat-3
 */

@XmlRootElement(name = "addEmployee", namespace = "http://tommy.dmi.com")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addEmployee", namespace = "http://tommy.dmi.com", propOrder = {"arg0", "arg1"})

public class AddEmployee {

    @XmlElement(name = "arg0")
    private com.dmi.tommy.Employee arg0;
    @XmlElement(name = "arg1")
    private com.dmi.tommy.Employee arg1;

    public com.dmi.tommy.Employee getArg0() {
        return this.arg0;
    }

    public void setArg0(com.dmi.tommy.Employee newArg0)  {
        this.arg0 = newArg0;
    }

    public com.dmi.tommy.Employee getArg1() {
        return this.arg1;
    }

    public void setArg1(com.dmi.tommy.Employee newArg1)  {
        this.arg1 = newArg1;
    }

}

