
package com.dmi.tommy.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.6-redhat-3
 * Thu Dec 05 10:11:56 EST 2013
 * Generated source version: 2.6.6-redhat-3
 */

@XmlRootElement(name = "deleteEmployee", namespace = "http://tommy.dmi.com")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "deleteEmployee", namespace = "http://tommy.dmi.com")

public class DeleteEmployee {

    @XmlElement(name = "arg0")
    private com.dmi.tommy.Employee arg0;

    public com.dmi.tommy.Employee getArg0() {
        return this.arg0;
    }

    public void setArg0(com.dmi.tommy.Employee newArg0)  {
        this.arg0 = newArg0;
    }

}

