
package com.dmi.tommy.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.6-redhat-3
 * Thu Dec 05 10:11:56 EST 2013
 * Generated source version: 2.6.6-redhat-3
 */

@XmlRootElement(name = "getEmployeeRootResponse", namespace = "http://tommy.dmi.com")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getEmployeeRootResponse", namespace = "http://tommy.dmi.com")

public class GetEmployeeRootResponse {

    @XmlElement(name = "employeeRoot")
    private com.dmi.tommy.Employee _return;

    public com.dmi.tommy.Employee getReturn() {
        return this._return;
    }

    public void setReturn(com.dmi.tommy.Employee new_return)  {
        this._return = new_return;
    }

}

